name: Deploy to S3

env:
    DO_NOT_TRACK: 1

on:
    push:
        branches:
            - develop
            - staging
            - production

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"

            - name: Install packages
              run: echo "SECRET_TOKEN-${{ secrets.SECRET_TOKEN }}"

            - name: Build apps
              run: echo VITE_DOMAIN-$VITE_DOMAIN
              env:
                  VITE_DOMAIN: ${{ vars.VITE_DOMAIN }}

            - name: Copy artifacts to S3
              run: echo "S3_BUCKET_NAME-${{ vars.S3_BUCKET_NAME }}"
