name: Deploy to S3

env:
    DO_NOT_TRACK: 1

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        environment: develop
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: ref name
              run: echo "SECRET_TOKEN-${{ github.ref_name }}"
              
            - name: Install packages
              run: echo "SECRET_TOKEN-${{ secrets.SECRET_TOKEN }}"

            - uses: 1arp/create-a-file-action@0.4.5
              with:
                  path: 'dist'
                  isAbsolutePath: false
                  file: 'index.html'
                  content: |
                    Hello ${{ vars.VITE_DOMAIN }}

            - name: Build apps
              run: echo VITE_DOMAIN-$VITE_DOMAIN
              env:
                  VITE_DOMAIN: ${{ vars.VITE_DOMAIN }}

            - uses: actions/upload-artifact@v2
              with:
                name: build-artifact
                path: dist

    deploy-to-dev:
        runs-on: ubuntu-latest
        environment: develop
        needs: [build]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/download-artifact@v2
              with:
                 name: build-artifact
                 path: dist
                      
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: ref name
              run: echo "SECRET_TOKEN-${{ github.ref_name }}"

            - name: check file
              run: cat dist/index.html
              
            - name: Copy artifacts to S3
              run: echo "S3_BUCKET_NAME-${{ vars.S3_BUCKET_NAME }}"

    deploy-to-stg:
        runs-on: ubuntu-latest
        environment: staging
        needs: [deploy-to-dev]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/download-artifact@v2
              with:
                 name: build-artifact
                 path: dist
                 
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: ref name
              run: echo "SECRET_TOKEN-${{ github.ref_name }}"

            - name: check file
              run: cat dist/index.html
              
            - name: Copy artifacts to S3
              run: echo "S3_BUCKET_NAME-${{ vars.S3_BUCKET_NAME }}"

    deploy-to-prod:
        runs-on: ubuntu-latest
        environment: production
        needs: [deploy-to-stg]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/download-artifact@v2
              with:
                 name: build-artifact
                 path: dist
                 
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: ref name
              run: echo "SECRET_TOKEN-${{ github.ref_name }}"

            - name: check file
              run: cat dist/index.html
              
            - name: Copy artifacts to S3
              run: echo "S3_BUCKET_NAME-${{ vars.S3_BUCKET_NAME }}"
